language: cpp
dist: bionic
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: lcov

script: ./build.sh

after_success:
- cd build
- make test
- make gcov
- make lcov
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

