coverage:
  ignore:
    - "./tests/**"
    - "./third_party/**"
    - "**/catch_reporter_tap.hpp"
    - "**/catch_reporter_automake.hpp"
    - "**/catch_reporter_teamcity.hpp"
    - "**/catch_reporter_sonarqube.hpp"
    - "**/external/clara.hpp"


codecov:
  branch: master

comment:
  layout: "diff"
