import enum
from collections.abc import Mapping, MutableMapping
from typing import TypeAlias, overload

class CoordRefPoint(enum.Enum):
    LeftMargin = 0
    RightMargin = 1
    TopMargin = 2
    BottomMargin = 3
    Center = 4

class CompareOp(enum.Enum):
    LessThan = 0
    LessEqual = 1
    GreaterThan = 2
    GreaterEqual = 3
    Equal = 4
    NotEqual = 5

class TimeVar:
    def __init__(self, arg: str, /) -> None: ...
    @property
    def name(self) -> str: ...
    def to_string(self) -> str: ...
    def __sub__(self, arg: TimeVar, /) -> TimeDiff: ...

class FrameVar:
    def __init__(self, arg: str, /) -> None: ...
    @property
    def name(self) -> str: ...
    def to_string(self) -> str: ...
    def __sub__(self, arg: FrameVar, /) -> FrameDiff: ...

class ObjectVar:
    def __init__(self, arg: str, /) -> None: ...
    @property
    def name(self) -> str: ...
    def to_string(self) -> str: ...

def C_TIME() -> TimeVar: ...  # noqa: N802
def C_FRAME() -> TimeVar: ...  # noqa: N802

class RefPoint:
    def __init__(self, arg0: ObjectVar, arg1: CoordRefPoint, /) -> None: ...
    @property
    def object(self) -> ObjectVar: ...
    @property
    def crt(self) -> CoordRefPoint: ...
    def to_string(self) -> str: ...

class TimeDiff:
    def __init__(self, arg0: TimeVar, arg1: TimeVar, /) -> None: ...
    @property
    def lhs(self) -> TimeVar: ...
    @property
    def rhs(self) -> TimeVar: ...
    def to_string(self) -> str: ...

class FrameDiff:
    def __init__(self, arg0: FrameVar, arg1: FrameVar, /) -> None: ...
    @property
    def lhs(self) -> FrameVar: ...
    @property
    def rhs(self) -> FrameVar: ...
    def to_string(self) -> str: ...

Expr: TypeAlias = (
    ConstExpr
    | NotExpr
    | AndExpr
    | OrExpr
    | NextExpr
    | PreviousExpr
    | AlwaysExpr
    | HoldsExpr
    | EventuallyExpr
    | SometimesExpr
    | UntilExpr
    | SinceExpr
    | ReleaseExpr
    | BackToExpr
    | ExistsExpr
    | ForallExpr
    | FreezeExpr
    | TimeBoundExpr
    | FrameBoundExpr
    | ObjectIdCompareExpr
    | ClassCompareExpr
    | ProbCompareExpr
    | DistCompareExpr
    | LatLonCompareExpr
    | AreaCompareExpr
    | SpatialExistsExpr
    | SpatialForallExpr
)

class ConstExpr:
    def __init__(self, arg: bool, /) -> None: ...
    @property
    def value(self) -> bool: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class NotExpr:
    def __init__(self, arg: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class AndExpr:
    def __init__(self, arg: list[Expr], /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class OrExpr:
    def __init__(self, arg: list[Expr], /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class NextExpr:
    def __init__(self, arg: Expr, steps: int = 1) -> None: ...
    @property
    def steps(self) -> int: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class PreviousExpr:
    def __init__(self, arg: Expr, steps: int = 1) -> None: ...
    @property
    def steps(self) -> int: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class AlwaysExpr:
    def __init__(self, arg: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class HoldsExpr:
    def __init__(self, arg: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class EventuallyExpr:
    def __init__(self, arg: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SometimesExpr:
    def __init__(self, arg: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class UntilExpr:
    def __init__(self, arg0: Expr, arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SinceExpr:
    def __init__(self, arg0: Expr, arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __invert__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ReleaseExpr:
    def __init__(self, arg0: Expr, arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class BackToExpr:
    def __init__(self, arg0: Expr, arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ExistsExpr:
    def __init__(self, arg0: list[ObjectVar], arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ForallExpr:
    def __init__(self, arg0: list[ObjectVar], arg1: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class FreezeExpr:
    def __init__(self, arg0: TimeVar | None, arg1: FrameVar | None, arg2: Expr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class TimeBoundExpr:
    def __init__(self, arg0: TimeDiff, arg1: CompareOp, arg2: float, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    @property
    def value(self) -> float: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class FrameBoundExpr:
    def __init__(self, arg0: FrameDiff, arg1: CompareOp, arg2: int, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    @property
    def value(self) -> int: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ObjectIdCompareExpr:
    def __init__(self, arg0: ObjectVar, arg1: CompareOp, arg2: ObjectVar, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ClassFunc:
    def __init__(self, arg: ObjectVar, /) -> None: ...
    def to_string(self) -> str: ...

class ClassCompareExpr:
    def __init__(self, arg0: ClassFunc, arg1: CompareOp, arg2: int | ClassFunc, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class ProbFunc:
    def __init__(self, arg: ObjectVar, /) -> None: ...
    def to_string(self) -> str: ...

class ProbCompareExpr:
    def __init__(self, arg0: ProbFunc, arg1: CompareOp, arg2: float | ProbFunc, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class EuclideanDistFunc:
    def __init__(self, arg0: RefPoint, arg1: RefPoint, /) -> None: ...
    def to_string(self) -> str: ...

class DistCompareExpr:
    def __init__(self, arg0: EuclideanDistFunc, arg1: CompareOp, arg2: float, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    @property
    def rhs(self) -> float: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class LatFunc:
    def __init__(self, arg: RefPoint, /) -> None: ...
    def to_string(self) -> str: ...

class LonFunc:
    def __init__(self, arg: RefPoint, /) -> None: ...
    def to_string(self) -> str: ...

class LatLonCompareExpr:
    def __init__(self, arg0: LatFunc | LonFunc, arg1: CompareOp, arg2: float | LatFunc | LonFunc, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

SpatialExpr: TypeAlias = (
    EmptySetExpr | UniverseSetExpr | BBoxExpr | SpatialComplementExpr | SpatialUnionExpr | SpatialIntersectExpr
)

class EmptySetExpr:
    def __init__(self) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class UniverseSetExpr:
    def __init__(self) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class BBoxExpr:
    def __init__(self, arg: ObjectVar, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SpatialComplementExpr:
    def __init__(self, arg: SpatialExpr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SpatialUnionExpr:
    def __init__(self, arg: list[SpatialExpr], /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SpatialIntersectExpr:
    def __init__(self, arg: list[SpatialExpr], /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class AreaFunc:
    def __init__(self, arg: SpatialExpr, /) -> None: ...
    def to_string(self) -> str: ...

class AreaCompareExpr:
    def __init__(self, arg0: AreaFunc, arg1: CompareOp, arg2: float | AreaFunc, /) -> None: ...
    @property
    def op(self) -> CompareOp: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SpatialExistsExpr:
    def __init__(self, arg: SpatialExpr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

class SpatialForallExpr:
    def __init__(self, arg: SpatialExpr, /) -> None: ...
    def to_string(self) -> str: ...
    def __inver__(self) -> Expr: ...
    def __and__(self, arg: Expr, /) -> Expr: ...
    def __or__(self, arg: Expr, /) -> Expr: ...

def make_true() -> Expr: ...
def make_false() -> Expr: ...
def next(
    arg: Expr,
    steps: int = 1,
) -> Expr: ...
def previous(
    arg: Expr,
    steps: int = 1,
) -> Expr: ...
def always(arg: Expr, /) -> Expr: ...
def eventually(arg: Expr, /) -> Expr: ...
def holds(arg: Expr, /) -> Expr: ...
def sometimes(arg: Expr, /) -> Expr: ...
def until(arg0: Expr, arg1: Expr, /) -> Expr: ...
def since(arg0: Expr, arg1: Expr, /) -> Expr: ...
def release(arg0: Expr, arg1: Expr, /) -> Expr: ...
def backto(arg0: Expr, arg1: Expr, /) -> Expr: ...
def exists(arg0: list[ObjectVar], arg1: Expr, /) -> Expr: ...
def forall(arg0: list[ObjectVar], arg1: Expr, /) -> Expr: ...
@overload
def freeze(arg0: TimeVar, arg1: Expr, /) -> Expr: ...
@overload
def freeze(arg0: FrameVar, arg1: Expr, /) -> Expr: ...
@overload
def freeze(arg0: TimeVar, arg1: FrameVar, arg2: Expr, /) -> Expr: ...
def bbox(arg: ObjectVar, /) -> SpatialExpr: ...
def empty_set() -> SpatialExpr: ...
def universe() -> SpatialExpr: ...
def spatial_complement(arg: SpatialExpr, /) -> SpatialExpr: ...
def spatial_union(arg: list[SpatialExpr], /) -> SpatialExpr: ...
def spatial_intersect(arg: list[SpatialExpr], /) -> SpatialExpr: ...
def spatial_exists(arg: SpatialExpr, /) -> Expr: ...
def spatial_forall(arg: SpatialExpr, /) -> Expr: ...
def is_class(arg0: ObjectVar, arg1: int, /) -> Expr: ...
def is_not_class(arg0: ObjectVar, arg1: int, /) -> Expr: ...
def high_confidence(obj: ObjectVar, threshold: float = 0.8) -> Expr: ...
def low_confidence(obj: ObjectVar, threshold: float = 0.5) -> Expr: ...

UNBOUNDED: int = ...

class History:
    def __init__(self, arg: int, /) -> None: ...
    @property
    def frames(self) -> int: ...
    def to_string(self) -> str: ...
    def is_bounded(self) -> bool: ...

class Horizon:
    def __init__(self, arg: int, /) -> None: ...
    @property
    def frames(self) -> int: ...
    def to_string(self) -> str: ...
    def is_bounded(self) -> bool: ...

class MonitoringRequirements:
    def __init__(self) -> None: ...
    @property
    def history(self) -> History: ...
    @property
    def horizon(self) -> Horizon: ...
    def to_string(self) -> str: ...

def compute_requirements(
    formula: Expr,
    fps: float = 1.0,
) -> MonitoringRequirements: ...
def is_past_time_formula(arg: Expr, /) -> bool: ...

class RefPointType(enum.Enum):
    LeftMargin = 0

    RightMargin = 1

    TopMargin = 2

    BottomMargin = 3

    Center = 4

class BoundingBox:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...
    @property
    def xmin(self) -> float: ...
    @xmin.setter
    def xmin(self, arg: float, /) -> None: ...
    @property
    def xmax(self) -> float: ...
    @xmax.setter
    def xmax(self, arg: float, /) -> None: ...
    @property
    def ymin(self) -> float: ...
    @ymin.setter
    def ymin(self, arg: float, /) -> None: ...
    @property
    def ymax(self) -> float: ...
    @ymax.setter
    def ymax(self, arg: float, /) -> None: ...
    def area(self) -> float: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def center(self) -> tuple[float, float]: ...
    def __eq__(self, arg: object, /) -> bool: ...
    def __lt__(self, arg: BoundingBox, /) -> bool: ...

class Object:
    def __init__(self) -> None: ...
    @property
    def object_class(self) -> int: ...
    @object_class.setter
    def object_class(self, arg: int, /) -> None: ...
    @property
    def probability(self) -> float: ...
    @probability.setter
    def probability(self, arg: float, /) -> None: ...
    @property
    def bbox(self) -> BoundingBox: ...
    @bbox.setter
    def bbox(self, arg: BoundingBox, /) -> None: ...
    def __eq__(self, arg: object, /) -> bool: ...
    def __lt__(self, arg: Object, /) -> bool: ...

ObjectMap: TypeAlias = MutableMapping[str, Object]

class Frame:
    def __init__(self) -> None: ...
    @property
    def timestamp(self) -> float: ...
    @timestamp.setter
    def timestamp(self, arg: float, /) -> None: ...
    @property
    def frame_num(self) -> int: ...
    @frame_num.setter
    def frame_num(self, arg: int, /) -> None: ...
    @property
    def size_x(self) -> int: ...
    @size_x.setter
    def size_x(self, arg: int, /) -> None: ...
    @property
    def size_y(self) -> int: ...
    @size_y.setter
    def size_y(self, arg: int, /) -> None: ...
    @property
    def objects(self) -> ObjectMap: ...
    @objects.setter
    def objects(self, arg: Mapping[str, Object], /) -> None: ...
    def universe_bbox(self) -> BoundingBox: ...

def get_reference_point(bbox: BoundingBox, ref_type: RefPointType) -> tuple[float, float]: ...
def euclidean_distance(bbox1: BoundingBox, ref1: RefPointType, bbox2: BoundingBox, ref2: RefPointType) -> float: ...

class BooleanEvaluator:
    def __init__(self) -> None: ...
    def evaluate(self, formula: Expr, current_frame: Frame, history: list[Frame], horizon: list[Frame]) -> bool: ...

class OnlineMonitor:
    def __init__(self, formula: Expr, fps: float = 1.0) -> None: ...
    def evaluate(self, frame: Frame) -> bool: ...
    def is_monitorable(self) -> bool: ...
    def requirements(self) -> MonitoringRequirements: ...
