stages:
  - stage: compiler_tests
    displayName: "Test build the library on multiple compilers"
    dependsOn: []
    jobs:
      - job: build
        strategy:
          matrix:
            ubuntu-clang-9:
              VM_IMAGE: ubuntu-latest
              CC: clang-9
              CXX: clang++-9
            ubuntu-gcc:
              VM_IMAGE: ubuntu-latest
              CC: gcc
              CXX: g++
            macos-xcode-latest:
              VM_IMAGE: macos-latest
            windows-msvc-latest:
              VM_IMAGE: windows-latest
        pool:
          vmImage: '$(VM_IMAGE)'
        steps:
          - checkout: self
            submodules: true
          - bash: |
              export CC=$(CC)
              export CXX=$(CXX)
            condition: eq( variables['Agent.OS'], 'Linux' )
            displayName: "Set CC and CXX for Linux"
          - task: CMake@1
            displayName: "Run CMake"
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)/build'
