stages:
  - stage: unit_tests
    displayName: "Run unit tests"
    dependsOn: []
    jobs:
      - job: catch_test
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            submodules: true
          - task: CMake@1
            displayName: "CMake configure for testing/coverage"
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)/build'
              cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Debug -DPERCEMON_COVERAGE=ON'
          - task: CMake@1
            displayName: "CMake build"
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)/build'
              cmakeArgs: '--build . --config Debug'
          - script: ctest --output-on-failure
            displayName: "Run CTest"
            workingDirectory: '$(Build.SourcesDirectory)/build'
          - task: CMake@1
            displayName: "Generate gcov data"
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)/build'
              cmakeArgs: '--build . --config Debug --target gcov'
          - script: |
              bash <(curl -s https://codecov.io/bash) -X gcov
            displayName: 'Upload to codecov.io'
