stages:
  - stage: unit_tests
    displayName: "Run unit tests"
    dependsOn: []
    jobs:
      - job: catch_test
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            submodules: true
          - task: run-cmake@0
            displayName: "Run CMake"
            inputs:
              cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
              cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
              buildDirectory: '$(Build.SourcesDirectory)/build'
              cmakeBuildType: 'Debug'
          - script: ctest --output-on-failure
            displayName: "Run CTest"
            workingDirectory: '$(Build.SourcesDirectory)/build'

